### ISSUE TITLE
Päringute timeout konfigureeritavaks

### ISSUE THREAD

**Issue by MihkelAuv** [janno-p/FSharp.Data.XRoad#1]
Kasutame suure hoolega teie poolt loodud teeki, kuid meil on pisikene mure. Nimelt kui ühe päringuga edastatakse suurel hulgal andmeid, siis juhtub mõnikord, et timeout'i aeg jõuab enne kätte kui päring kogumahus edastatud. Kas oleks võimalik timeouti väärtus teha konfigureeritavaks teie teegis?

**Comment by janno-p** [comment]
Täiendasin `RequestReady` event-i parameetreid selliselt, et oleks võimalik saada juurdepääs kasutatavale `HttpWebRequest` objektile vahetult enne ühenduse loomist (al. versioonist 1.0.0-beta021). Selle kaudu on muu hulgas võimalik erinevaid timeout väärtuseid vajadusele vastavalt sättida:

```csharp
var service = new Estat.webService.port();
service.RequestReady += (o, e) => {
    e.Request.HttpWebRequest.Timeout = 100;
    e.Request.HttpWebRequest.ReadWriteTimeout = 100;
};
var response = service.ReturnError(hdr, "1234");
```
